
GW2UI_STORAGE = {
	["Alliance"] = {
		["ArgentDawn"] = {
			["CLASS"] = {
				["Minsohu"] = "MONK",
			},
			["MONEY"] = {
				["Minsohu"] = 8474472,
			},
		},
	},
}
GW2UI_SETTINGS_PROFILES = {
	[0] = {
		[true] = false,
		["USE_BATTLEGROUND_HUD"] = true,
		["MultiBarBottomLeft"] = {
			["relativePoint"] = "BOTTOM",
			["xOfs"] = -372,
			["point"] = "BOTTOMLEFT",
			["hideDefaultBackground"] = true,
			["yOfs"] = 120,
			["ButtonsPerRow"] = 6,
			["margin"] = 2,
			["size"] = 38,
		},
		["focus_BUFFS_FILTER_ALL"] = false,
		["INDICATORS_ICON"] = false,
		["RAID_WIDTH"] = 55,
		["ANCHOR_CURSOR_OFFSET_X"] = 0,
		["MINIMAP_ENABLED"] = true,
		["RAID_GROW"] = "DOWN+RIGHT",
		["USE_TALENT_WINDOW"] = true,
		["LOOTFRAME_POSITION"] = {
			["yOfs"] = 0,
			["xOfs"] = 0,
			["point"] = "BOTTOMLEFT",
			["relativePoint"] = "TOPLEFT",
		},
		["multibarright_x_position"] = -260,
		["BNTOASTFRAME_SKIN_ENABLED"] = true,
		["INDICATOR_TOPLEFT"] = {
			[0] = 0,
			[269] = 0,
		},
		["CLASS_POWER"] = true,
		["INDICATOR_TOPRIGHT"] = {
			[0] = 0,
			[269] = 0,
		},
		["HIDE_CHATSHADOW"] = false,
		["NPC_CAM_ENABLED"] = false,
		["BANK_POSITION"] = {
			["yOfs"] = -60,
			["xOfs"] = 60,
			["point"] = "TOPLEFT",
			["relativePoint"] = "TOPLEFT",
		},
		["target_TARGET_ENABLED"] = true,
		["SHOW_QUESTTRACKER_COMPASS"] = true,
		["RAID_UNIT_MARKERS"] = false,
		["focustarget_pos"] = {
			["yOfs"] = -161,
			["xOfs"] = 176,
			["point"] = "TOP",
			["relativePoint"] = "TOP",
		},
		["RAID_UNIT_HEALTH"] = "NONE",
		["TIMERTRACKER_SKIN_ENABLED"] = true,
		["DROPDOWNLIST_SKIN_ENABLED"] = true,
		["BANK_WIDTH"] = 720,
		["focus_DEBUFFS_FILTER"] = true,
		["RAID_CLASS_COLOR"] = false,
		["targettarget_pos"] = {
			["yOfs"] = -84,
			["xOfs"] = 175,
			["point"] = "TOP",
			["relativePoint"] = "TOP",
		},
		["LFGINVITEPOPUP_SKIN_ENABLED"] = true,
		["TALKINGHEAD_SKIN_ENABLED"] = true,
		["HERO_POSITION"] = {
			["yOfs"] = 0,
			["xOfs"] = 100,
			["point"] = "LEFT",
			["relativePoint"] = "LEFT",
		},
		["USE_CHAT_BUBBLES"] = false,
		["INDICATOR_TOP"] = {
			[0] = 0,
			[269] = 0,
		},
		["RAID_SORT_BY_ROLE"] = true,
		["pet_pos"] = {
			["yOfs"] = 134,
			["xOfs"] = -95,
			["point"] = "BOTTOMRIGHT",
			["relativePoint"] = "BOTTOMRIGHT",
		},
		["GameTooltipPos"] = {
			["yOfs"] = 189,
			["xOfs"] = -69,
			["point"] = "BOTTOMRIGHT",
			["relativePoint"] = "BOTTOMRIGHT",
		},
		["target_BUFFS"] = true,
		["CURSOR_ANCHOR_TYPE"] = "ANCHOR_CURSOR",
		["multibarleft_pos"] = {
			["yOfs"] = 0,
			["xOfs"] = -300,
			["point"] = "RIGHT",
			["relativePoint"] = "RIGHT",
		},
		["POWERBAR_ENABLED"] = true,
		["DISABLE_NAMEPLATES"] = false,
		["FADE_MULTIACTIONBAR_2"] = "ALWAYS",
		["target_CASTINGBAR_DATA"] = false,
		["MultiBarRight"] = {
			["relativePoint"] = "BOTTOMRIGHT",
			["xOfs"] = -6,
			["point"] = "BOTTOMRIGHT",
			["hideDefaultBackground"] = true,
			["yOfs"] = 33,
			["ButtonsPerRow"] = 1,
			["margin"] = 2,
			["size"] = 38,
		},
		["MULTIBAR_RIGHT_COLS"] = 1,
		["FADE_MICROMENU"] = false,
		["FOCUS_ENABLED"] = true,
		["HIDEACTIONBAR_BACKGROUND_ENABLED"] = false,
		["MINIMAP_POS"] = "TOP",
		["target_BUFFS_FILTER_ALL"] = false,
		["PETBAR_ENABLED"] = true,
		["target_BUFFS_FILTER"] = true,
		["INDICATOR_CENTER"] = {
			[0] = 0,
			[269] = 0,
		},
		["AURAS_MISSING"] = "Power Word: Fortitude, Battle Shout, Arcane Intellect",
		["LFGDUNGEONREADYDIALOG_SKIN_ENABLED"] = true,
		["HIDE_QUESTVIEW"] = false,
		["TOOLTIPS_ENABLED"] = true,
		["GHOSTFRAME_SKIN_ENABLED"] = true,
		["RAID_UNITS_PER_COLUMN"] = 5,
		["ACTIONBARS_ENABLED"] = true,
		["focus_HEALTH_VALUE_TYPE"] = false,
		["MAINMENU_SKIN_ENABLED"] = true,
		["profileCreatedDate"] = "04/23/20 22:47:53",
		["LFGLISTINVITEDIALOG_SKIN_ENABLED"] = true,
		["target_y_position"] = -100,
		["focus_y_position"] = -100,
		["CASTINGBAR_ENABLED"] = true,
		["MINIMAP_SCALE"] = 170,
		["AURAS_IGNORED"] = "Exhaustion, Sated, Temporal Displacement, Fatigued",
		["NAMEPLATES_ENABLED"] = true,
		["DYNAMIC_CAM"] = false,
		["FADE_MULTIACTIONBAR_1"] = "ALWAYS",
		["MINIMAP_FPS"] = false,
		["QUEUESTATUSFRAME_SKIN_ENABLED"] = true,
		["focus_HEALTH_VALUE_ENABLED"] = false,
		["LFGLISTAPPLICATIONDIALOG_SKIN_ENABLED"] = true,
		["MINIMAP_HOVER"] = "NONE",
		["MultiBarBottomRight"] = {
			["relativePoint"] = "BOTTOM",
			["xOfs"] = 372,
			["point"] = "BOTTOMRIGHT",
			["hideDefaultBackground"] = true,
			["yOfs"] = 120,
			["ButtonsPerRow"] = 6,
			["margin"] = 2,
			["size"] = 38,
		},
		["BAG_WIDTH"] = 480,
		["DISABLE_CHATFRAME"] = false,
		["BORDER_ENABLED"] = true,
		["target_ILVL"] = false,
		["raid_pos"] = {
			["yOfs"] = -36,
			["xOfs"] = 5,
			["point"] = "TOPLEFT",
			["relativePoint"] = "TOPLEFT",
		},
		["PETBAR_LOCKED"] = false,
		["CASTINGBAR_DATA"] = false,
		["CHATFRAME_FADE"] = true,
		["INDICATOR_RIGHT"] = {
			[0] = 0,
			[269] = 0,
		},
		["GROUP_FRAMES"] = true,
		["PLAYER_BUFFS_ENABLED"] = true,
		["RAID_ANCHOR"] = "POSITION",
		["QUESTVIEW_ENABLED"] = true,
		["HUD_SCALE"] = 0.8,
		["RAID_AURA_TOOLTIP_IN_COMBAT"] = true,
		["target_AURAS_ON_TOP"] = false,
		["INDICATOR_LEFT"] = {
			[0] = 0,
			[269] = 0,
		},
		["BAG_ITEM_SIZE"] = 40,
		["BAG_ITEM_BORDER_HIDE"] = true,
		["STANCEBAR_POSITION"] = "LEFT",
		["HUD_SPELL_SWAP"] = true,
		["RAID_STYLE_PARTY"] = false,
		["GW2_UI_VERSION"] = "GW2_UI v5.2.3",
		["HEALTHGLOBE_ENABLED"] = true,
		["DISABLE_TOOLTIPS"] = false,
		["READYCHECKLISTENERFRAME_SKIN_ENABLED"] = true,
		["MultiBarLeft"] = {
			["relativePoint"] = "BOTTOMRIGHT",
			["xOfs"] = -46,
			["point"] = "BOTTOMRIGHT",
			["hideDefaultBackground"] = true,
			["yOfs"] = 33,
			["ButtonsPerRow"] = 1,
			["margin"] = 2,
			["size"] = 38,
		},
		["FONTS_ENABLED"] = true,
		["ANCHOR_CURSOR_OFFSET_Y"] = 0,
		["multibarright_y_position"] = 0,
		["RAID_POWER_BARS"] = false,
		["GEARMANAGERDIALOGPOPUP_SKIN_ENABLED"] = true,
		["CHATFRAME_ENABLED"] = true,
		["FADE_MULTIACTIONBAR_3"] = "ALWAYS",
		["target_HEALTH_VALUE_TYPE"] = false,
		["focus_BUFFS"] = true,
		["RAID_ONLY_DISPELL_DEBUFFS"] = false,
		["TARGET_ENABLED"] = true,
		["profilename"] = "Yucca",
		["PlayerBuffFrame_GrowDirection"] = "UP",
		["profileCreatedCharacter"] = "Minsohu",
		["target_THREAT_VALUE_ENABLED"] = false,
		["DEATHRECAPFRAME_SKIN_ENABLED"] = true,
		["RAID_CONT_HEIGHT"] = 0,
		["multibarright_pos"] = {
			["yOfs"] = 0,
			["xOfs"] = -260,
			["point"] = "RIGHT",
			["relativePoint"] = "RIGHT",
		},
		["CHATBUBBLES_ENABLED"] = true,
		["PlayerBuffFrame"] = {
			["yOfs"] = 31,
			["xOfs"] = -94,
			["point"] = "BOTTOMRIGHT",
			["relativePoint"] = "BOTTOMRIGHT",
		},
		["multibarleft_y_position"] = 0,
		["target_HEALTH_VALUE_ENABLED"] = false,
		["BUTTON_ASSIGNMENTS"] = true,
		["focus_DEBUFFS"] = true,
		["RAID_CONT_WIDTH"] = 0,
		["RAID_HEIGHT"] = 47,
		["PIXEL_PERFECTION"] = true,
		["ACTIVE_PROFILE"] = 0,
		["profileLastUpdated"] = "04/23/20 23:00:29",
		["focus_CLASS_COLOR"] = true,
		["target_x_position"] = -100,
		["BAGS_ENABLED"] = true,
		["target_DEBUFFS"] = true,
		["target_CLASS_COLOR"] = true,
		["DROPDOWNMENU_SKIN_ENABLED"] = true,
		["WORLD_MARKER_FRAME"] = true,
		["BAG_POSITION"] = {
			["yOfs"] = -60,
			["xOfs"] = -20,
			["point"] = "TOPRIGHT",
			["relativePoint"] = "TOPRIGHT",
		},
		["PET_ENABLED"] = true,
		["castingbar_pos"] = {
			["yOfs"] = 143,
			["xOfs"] = 0,
			["point"] = "BOTTOM",
			["relativePoint"] = "BOTTOM",
		},
		["target_pos"] = {
			["yOfs"] = -35,
			["xOfs"] = -15,
			["point"] = "TOPLEFT",
			["relativePoint"] = "TOPLEFT",
		},
		["FADE_MULTIACTIONBAR_4"] = "ALWAYS",
		["focus_x_position"] = -350,
		["target_HOOK_COMBOPOINTS"] = false,
		["QUESTTRACKER_ENABLED"] = true,
		["focus_pos"] = {
			["yOfs"] = -1,
			["xOfs"] = 174,
			["point"] = "TOP",
			["relativePoint"] = "TOP",
		},
		["focus_TARGET_ENABLED"] = true,
		["STATICPOPUP_SKIN_ENABLED"] = true,
		["focus_BUFFS_FILTER"] = true,
		["BANK_REVERSE_SORT"] = false,
		["INDICATOR_BAR"] = {
			[0] = 0,
			[256] = 194384,
			[269] = 0,
		},
		["BAG_REVERSE_SORT"] = true,
		["RAID_UNIT_FLAGS"] = "NONE",
		["USE_CHARACTER_WINDOW"] = true,
		["LFGDUNGEONREADYSTATUS_SKIN_ENABLED"] = true,
		["XPBAR_ENABLED"] = true,
		["target_DEBUFFS_FILTER"] = true,
		["INDICATORS_TIME"] = true,
		["TOOLTIP_MOUSE"] = false,
		["multibarleft_x_position"] = -300,
	},
}
