
Musician_Settings = {
	["crossRP_HintShown"] = true,
	["minimap"] = {
		["minimapPos"] = 214.3456289698231,
		["hide"] = false,
	},
	["showNamePlateIcon"] = true,
	["mutedPlayers"] = {
	},
	["keyboardVisible"] = true,
	["trp3MapScan"] = true,
	["debug"] = {
	},
	["enableEmote"] = true,
	["cinematicModeNamePlates"] = false,
	["nextSongId"] = 29,
	["emoteHintShown"] = true,
	["keyboardIsConfigured"] = {
		["Windows"] = false,
	},
	["muteGameMusic"] = true,
	["keyboardMapping"] = {
		["Windows"] = {
			["F11"] = "F11",
			["LALT"] = "AltLeft",
			["LSHIFT"] = "ShiftLeft",
			["RSHIFT"] = "ShiftRight",
			["RMETA"] = "MetaRight",
			["F10"] = "F10",
			["BACKSPACE"] = "Backspace",
			["WriteProgram"] = "WriteProgram",
			["ENTER"] = "Enter",
			["RCTRL"] = "ControlRight",
			["SPACE"] = "Space",
			["LCTRL"] = "ControlLeft",
			["LMETA"] = "MetaLeft",
			["F1"] = "F1",
			["F2"] = "F2",
			["F3"] = "F3",
			["F5"] = "F5",
			["F4"] = "F4",
			["F7"] = "F7",
			["F6"] = "F6",
			["DELETE"] = "Delete",
			["RALT"] = "AltRight",
			["MENU"] = "ContextMenu",
			["F12"] = "F12",
			["TAB"] = "Tab",
			["CAPSLOCK"] = "CapsLock",
			["F8"] = "F8",
			["F9"] = "F9",
		},
	},
	["hideNamePlateBars"] = true,
	["namePlatesHintShown"] = true,
	["enableEmotePromo"] = true,
	["enableTipsAndTricks"] = true,
	["cinematicMode"] = true,
	["muteInstrumentToys"] = true,
}
