
TRP3_Profiles = {
	["04172110102jBOC"] = {
		["inventory"] = {
			["init"] = true,
			["id"] = "main",
			["totalWeight"] = 500,
			["content"] = {
				["17"] = {
					["id"] = "bag",
					["totalWeight"] = 500,
					["content"] = {
					},
					["totalValue"] = 0,
				},
			},
			["totalValue"] = 0,
		},
		["player"] = {
			["characteristics"] = {
				["IC"] = "inv_misc_hearthstonecard_legendary",
				["RS"] = 0,
				["MI"] = {
				},
				["FN"] = "OOC",
				["PS"] = {
				},
				["v"] = 6,
			},
			["character"] = {
				["CU"] = "",
				["CO"] = "",
				["RP"] = 2,
				["LC"] = "enUS",
				["XP"] = 1,
				["v"] = 5,
			},
			["about"] = {
				["T2"] = {
				},
				["T3"] = {
					["PH"] = {
					},
					["PS"] = {
					},
					["HI"] = {
					},
				},
				["TE"] = 1,
				["T1"] = {
				},
				["v"] = 1,
			},
			["misc"] = {
				["ST"] = {
					["1"] = 5,
					["3"] = 0,
					["2"] = 0,
					["5"] = 0,
					["4"] = 0,
					["6"] = 0,
				},
				["PE"] = {
				},
				["v"] = 8,
			},
		},
		["questlog"] = {
		},
		["notes"] = {
		},
		["profileName"] = "_OOC",
	},
	["1016222047a3dXy"] = {
		["inventory"] = {
			["init"] = true,
			["id"] = "main",
			["totalWeight"] = 500,
			["content"] = {
				["17"] = {
					["id"] = "bag",
					["totalWeight"] = 500,
					["content"] = {
					},
					["totalValue"] = 0,
				},
			},
			["totalValue"] = 0,
		},
		["player"] = {
			["characteristics"] = {
				["CL"] = "Monk",
				["RA"] = "Pandaren",
				["PS"] = {
				},
				["MI"] = {
				},
				["FN"] = "Minsohu",
				["IC"] = "Achievement_Guild_ClassyPanda",
				["v"] = 227,
			},
			["character"] = {
				["RP"] = 2,
				["LC"] = "enUS",
				["XP"] = 2,
				["v"] = 4,
			},
			["misc"] = {
				["PE"] = {
				},
				["ST"] = {
				},
				["v"] = 1,
			},
			["about"] = {
				["T2"] = {
				},
				["T3"] = {
					["PH"] = {
					},
					["PS"] = {
					},
					["HI"] = {
					},
				},
				["TE"] = 1,
				["T1"] = {
				},
				["v"] = 1,
			},
		},
		["questlog"] = {
		},
		["profileName"] = "Default profile",
	},
	["0327213047JZwig"] = {
		["inventory"] = {
			["init"] = true,
			["id"] = "main",
			["totalWeight"] = 500,
			["content"] = {
				["17"] = {
					["id"] = "bag",
					["totalWeight"] = 500,
					["content"] = {
					},
					["totalValue"] = 0,
				},
			},
			["totalValue"] = 0,
		},
		["player"] = {
			["characteristics"] = {
				["RA"] = "Human",
				["LN"] = "Character",
				["MI"] = {
				},
				["PS"] = {
				},
				["v"] = 4,
				["CL"] = "Banker",
				["FN"] = "Banker",
				["RS"] = 0,
				["TI"] = "Just a",
				["IC"] = "inv_misc_coin_02",
				["CH"] = "ffffff",
			},
			["character"] = {
				["v"] = 7,
				["CO"] = "",
				["RP"] = 2,
				["LC"] = "enUS",
				["XP"] = 1,
				["CU"] = "",
			},
			["misc"] = {
				["PE"] = {
				},
				["ST"] = {
					["1"] = 5,
					["3"] = 0,
					["2"] = 0,
					["5"] = 0,
					["4"] = 0,
					["6"] = 0,
				},
				["v"] = 8,
			},
			["about"] = {
				["T2"] = {
				},
				["T3"] = {
					["PH"] = {
					},
					["PS"] = {
					},
					["HI"] = {
					},
				},
				["TE"] = 1,
				["T1"] = {
				},
				["v"] = 1,
			},
		},
		["questlog"] = {
		},
		["profileName"] = "_Just Banker",
	},
	["0301221101jbTao"] = {
		["inventory"] = {
			["init"] = true,
			["id"] = "main",
			["totalWeight"] = 500,
			["content"] = {
				["17"] = {
					["yOfs"] = -56.16881561279297,
					["xOfs"] = -270.4979248046875,
					["point"] = "RIGHT",
					["totalValue"] = 0,
					["id"] = "bag",
					["totalWeight"] = 500,
					["content"] = {
					},
					["relativePoint"] = "RIGHT",
				},
			},
			["totalValue"] = 0,
		},
		["notes"] = {
			["0301221101jbTao"] = "Money: 0g 46s 17c\n\nMonk master: Chiu.\n\nRobbed pandaren: Xi-Han",
		},
		["profileName"] = "Wade Tosmun",
		["questlog"] = {
			["coinCampaign"] = {
				["NPC"] = {
				},
				["QUEST"] = {
				},
			},
			["042423290735q8X"] = {
				["NPC"] = {
				},
				["QUEST"] = {
					["quest_1_first"] = {
						["CS"] = "step_1_first",
						["OB"] = {
						},
					},
				},
			},
		},
		["player"] = {
			["characteristics"] = {
				["LN"] = "Tosmun",
				["MI"] = {
					{
						["IC"] = "inv_misc_tabard_gilneas",
						["NA"] = "Accent",
						["VA"] = "Gilnean",
					}, -- [1]
				},
				["FN"] = "Wade",
				["RS"] = 0,
				["IC"] = "inv_fistofthewhitetiger",
				["EH"] = "3c4d1c",
				["HE"] = "Medium",
				["CH"] = "00d357",
				["RA"] = "Gilnean Human",
				["BP"] = "Duskhaven - Gilneas",
				["v"] = 44,
				["RE"] = "Tushui bunkhouse - Stormwind",
				["AG"] = "26",
				["TI"] = "\"Doctor\"",
				["CL"] = " ",
				["EC"] = "Green",
				["FT"] = "Field medic || Monk trainee",
				["PS"] = {
				},
				["WE"] = "Slim",
			},
			["character"] = {
				["v"] = 62,
				["CO"] = "",
				["RP"] = 1,
				["LC"] = "enUS",
				["XP"] = 2,
				["CU"] = "-Right arm in sling\n",
			},
			["misc"] = {
				["PE"] = {
					["1"] = {
						["AC"] = true,
						["TI"] = "Weapons",
						["IC"] = "inv_sword_27",
						["TX"] = "-Gladius on back (if equipped).\n-Hardened joints on gloves.\n-Attachable spikes for right glove.\n-Revolver on right side of waist.",
					},
					["3"] = {
						["AC"] = true,
						["TI"] = "Injuries",
						["IC"] = "spell_druid_bloodythrash",
						["TX"] = "-Broken right arm\n",
					},
					["2"] = {
						["AC"] = false,
						["TI"] = "Equipment",
						["IC"] = "inv_misc_bag_07",
						["TX"] = "-Small satchel on back side of waist.",
					},
					["5"] = {
						["IC"] = "inv_drink_waterskin_05",
						["TI"] = "Waterskin",
						["TX"] = "Waterskin containing some beverage.",
						["AC"] = false,
					},
					["4"] = {
						["AC"] = false,
						["TI"] = "Injuries",
						["IC"] = "spell_druid_bloodythrash",
						["TX"] = "-Healed stab wound in right shoulder.",
					},
				},
				["ST"] = {
					["1"] = 4,
					["3"] = 3,
					["2"] = 1,
					["5"] = 0,
					["4"] = 0,
					["6"] = 2,
				},
				["v"] = 89,
			},
			["about"] = {
				["T2"] = {
				},
				["T3"] = {
					["PH"] = {
						["BK"] = 1,
					},
					["PS"] = {
						["BK"] = 1,
					},
					["HI"] = {
						["BK"] = 1,
					},
				},
				["TE"] = 1,
				["T1"] = {
					["TX"] = "",
				},
				["BK"] = 1,
				["v"] = 5,
			},
		},
		["relation"] = {
			["0227163808I0k6a"] = "FRIEND",
			["10072210205Tiuy"] = "FRIEND",
			["1016130636GXilL"] = "FRIEND",
			["1126204212IMJI7"] = "FRIEND",
			["03161302558OHAM"] = "BUSINESS",
			["0810180446rb90c"] = "BUSINESS",
			["0719125548aZ7TY"] = "UNFRIENDLY",
			["0304000817JfzSd"] = "FRIEND",
			["0608012126aNpXr"] = "FRIEND",
			["0302005803fTMyw"] = "FRIEND",
			["0408190906dkVod"] = "FRIEND",
			["1109192359VRuPb"] = "FRIEND",
			["04241252074LzP9"] = "NEUTRAL",
			["0421210646ANxLX"] = "FRIEND",
			["0329205832Gidfc"] = "NEUTRAL",
			["11280322062X271"] = "FRIEND",
			["0422135637M1wug"] = "NEUTRAL",
			["0126183251L6mLU"] = "FRIEND",
			["0331082350H9Dlu"] = "FRIEND",
			["0421124632eyzLE"] = "FRIEND",
			["06052228105TqYg"] = "FRIEND",
			["0706000137bgK2a"] = "BUSINESS",
			["12112031452WfU0"] = "NEUTRAL",
			["0514191418NGnPZ"] = "BUSINESS",
			["0309182257czk9c"] = "NEUTRAL",
			["0325134730x9jZU"] = "FRIEND",
			["1123235404FRD4L"] = "NEUTRAL",
			["1118151851QiWqk"] = "FRIEND",
			["0218094111URTwa"] = "FRIEND",
			["1124233901VFlQO"] = "FRIEND",
			["04191657255GVHJ"] = "NEUTRAL",
		},
	},
	["0429003812dNQzx"] = {
		["inventory"] = {
			["init"] = true,
			["id"] = "main",
			["totalWeight"] = 3850,
			["content"] = {
				["17"] = {
					["relativePoint"] = "RIGHT",
					["totalWeight"] = 3850,
					["point"] = "RIGHT",
					["totalValue"] = 600000,
					["yOfs"] = -103.6961975097656,
					["xOfs"] = -81.46839141845703,
					["content"] = {
						["1"] = {
							["id"] = "042100145564xVd",
						},
						["3"] = {
							["id"] = "04191950437OgCA",
							["count"] = 50,
						},
						["2"] = {
							["id"] = "0419204257wizik",
							["count"] = 6,
						},
					},
					["id"] = "bag",
				},
			},
			["totalValue"] = 600000,
		},
		["player"] = {
			["characteristics"] = {
				["MI"] = {
				},
				["RA"] = "Tauren",
				["EC"] = "Dark brown",
				["LN"] = "Spiritshout",
				["BP"] = "Barrens",
				["FN"] = "Yenuthile",
				["EH"] = "281903",
				["AG"] = "Adult",
				["IC"] = "ability_shaman_tranquilmindtotem",
				["v"] = 26,
				["PS"] = {
				},
				["RS"] = 0,
				["CL"] = "Rambler",
				["FT"] = "Rambler || Drunken treehugger || Accidental shaman",
				["HE"] = "Average",
				["CH"] = "203c18",
			},
			["character"] = {
				["CU"] = "-Tipsy",
				["CO"] = "-Walkups welcome",
				["RP"] = 1,
				["LC"] = "enUS",
				["XP"] = 2,
				["v"] = 37,
			},
			["misc"] = {
				["PE"] = {
					["1"] = {
						["IC"] = "achievement_character_tauren_male",
						["TI"] = "Appearance",
						["TX"] = "-Long diagonal scar over the face",
						["AC"] = true,
					},
					["3"] = {
						["AC"] = false,
						["TI"] = "Leather Armor",
						["TX"] = "-Light leather armor\n-Leather pauldrons\n-Leather headress",
						["IC"] = "inv_armor_tauren_d_01glove",
					},
					["2"] = {
						["AC"] = true,
						["TI"] = "Weapons",
						["TX"] = "-Spear (if equiped)\n-Long staff\n-Tomahawk\n-Hunting knife",
						["IC"] = "inv_polearm_2h_heirloomspear_c_01",
					},
					["5"] = {
						["AC"] = false,
						["TI"] = "Injuries",
						["IC"] = "spell_druid_bloodythrash",
					},
					["4"] = {
						["AC"] = false,
						["TI"] = "Warpaint",
						["IC"] = "inv_inscription_warpaint_blue",
						["TX"] = "-Tireless Eagle (Air)",
					},
				},
				["ST"] = {
					["1"] = 3,
					["3"] = 3,
					["2"] = 1,
					["5"] = 4,
					["4"] = 0,
					["6"] = 1,
				},
				["v"] = 75,
			},
			["about"] = {
				["T2"] = {
				},
				["T3"] = {
					["PH"] = {
						["BK"] = 1,
					},
					["PS"] = {
						["BK"] = 1,
					},
					["HI"] = {
						["BK"] = 1,
					},
				},
				["TE"] = 1,
				["T1"] = {
					["TX"] = "HP: 6\nAdrenalin: 3\nMana: 1\n\nRacial: Earthmother's bounty: 15+ to environmental checks.",
				},
				["BK"] = 1,
				["v"] = 6,
			},
		},
		["relation"] = {
			["1017144954Hgs5M"] = "FRIEND",
			["11292146219ouTY"] = "UNFRIENDLY",
			["0206191809Qysyw"] = "BUSINESS",
			["1006215730FTftA"] = "NEUTRAL",
			["0303201423Sgf7Y"] = "FRIEND",
			["1023051747xz0qn"] = "FRIEND",
			["0506030854tAPlI"] = "NEUTRAL",
			["0921183859UxAFr"] = "FRIEND",
			["0222232006Snj7T"] = "NEUTRAL",
			["0713053637JegDW"] = "NEUTRAL",
			["05141855065XzmW"] = "NEUTRAL",
			["0424120814axIg4"] = "FRIEND",
			["0301200606tohPk"] = "BUSINESS",
			["0412182512rnkA4"] = "NEUTRAL",
			["1018155025lg07d"] = "FRIEND",
			["1025155315feFkw"] = "FRIEND",
			["09012120135EqX4"] = "NEUTRAL",
			["1016211654nfWaD"] = "BUSINESS",
			["1024194017h5zjx"] = "NEUTRAL",
			["08101856494nRAN"] = "FRIEND",
			["0930140441qxuyV"] = "NEUTRAL",
			["1016224719Enqtr"] = "FRIEND",
			["1203174212ekCom"] = "BUSINESS",
			["03142252355i9q5"] = "FRIEND",
			["0220030547rExr7"] = "NEUTRAL",
			["0305173449QGBEo"] = "NEUTRAL",
			["0926002241LI9Qq"] = "BUSINESS",
			["0430044455r9mTF"] = "FRIEND",
			["0605213800SghF1"] = "FRIEND",
			["10241932338arEp"] = "UNFRIENDLY",
			["1017163945yWqVp"] = "BUSINESS",
			["0203163303U6cW1"] = "NEUTRAL",
			["0322002331O70Mb"] = "BUSINESS",
			["10011915550Rwy7"] = "NEUTRAL",
			["0305145452oyb2R"] = "UNFRIENDLY",
			["1023213147ysYf2"] = "FRIEND",
			["1014125914BkJEv"] = "NEUTRAL",
			["1016122415o9xsz"] = "NEUTRAL",
			["07092019281b4YD"] = "NEUTRAL",
			["10231637039JSNH"] = "NEUTRAL",
			["0103175543OhKMB"] = "BUSINESS",
			["1002152540i2aNM"] = "BUSINESS",
			["0628211112Xtw8z"] = "FRIEND",
			["1228222617Pgpl8"] = "BUSINESS",
		},
		["questlog"] = {
		},
		["notes"] = {
			["0429003812dNQzx"] = "An'she - sun (679 hides)\nMu'sha - Elune - moon\n\nWarpaint:\nRed: War/Sucess/Energy/Strength\nBlue: Confidence\nGreen: Endurance\n\nYenuthile's mother - Tahki Springstream\nYenuthile's father - Ashnkii Spiritshout\n\nYenuthile's mother lives in Sun Rock Retreat in Stonetalon Mountains.\n\nRoyal Exchange room 217\n\n\n\n\n",
		},
		["profileName"] = "Yenuthile",
	},
	["0307210639PPtAO"] = {
		["inventory"] = {
			["init"] = true,
			["id"] = "main",
			["totalWeight"] = 500,
			["content"] = {
				["17"] = {
					["id"] = "bag",
					["totalWeight"] = 500,
					["content"] = {
					},
					["totalValue"] = 0,
				},
			},
			["totalValue"] = 0,
		},
		["player"] = {
			["characteristics"] = {
				["RA"] = "Tauren",
				["LN"] = "Spiritshout",
				["MI"] = {
				},
				["PS"] = {
				},
				["v"] = 6,
				["IC"] = "inv_ammo_arrow_01",
				["FN"] = "Ohannsho",
				["RS"] = 0,
				["CL"] = "Fletcher",
				["CH"] = "9cac30",
			},
			["character"] = {
				["v"] = 67,
				["CO"] = "",
				["RP"] = 1,
				["LC"] = "enUS",
				["XP"] = 2,
				["CU"] = "-Drunk",
			},
			["misc"] = {
				["PE"] = {
					["1"] = {
						["IC"] = "achievement_character_tauren_female",
						["TI"] = "Appearance",
						["TX"] = "-Strangely familiar",
						["AC"] = false,
					},
					["5"] = {
						["AC"] = false,
						["TI"] = "Injuries",
						["IC"] = "spell_druid_bloodythrash",
					},
					["3"] = {
						["AC"] = false,
						["TI"] = "Leather plate Armor",
						["TX"] = "-Armor made of leather plates\n-Leather is dyed green\n-Only left shoulder protected",
						["IC"] = "inv_chest_leather_raidmonk_q_01",
					},
					["2"] = {
						["AC"] = false,
						["TI"] = "Weapons",
						["TX"] = "-Simple looking shortbow on back\n-Long walking stick on back\n-Primitive dagger on left thigh\n-Quiver with arrows on right thigh",
						["IC"] = "inv_archaeology_70_tauren_stonewoodbow",
					},
				},
				["ST"] = {
					["1"] = 0,
					["3"] = 0,
					["2"] = 0,
					["5"] = 0,
					["4"] = 0,
					["6"] = 0,
				},
				["v"] = 22,
			},
			["about"] = {
				["T2"] = {
				},
				["T3"] = {
					["PH"] = {
					},
					["PS"] = {
					},
					["HI"] = {
					},
				},
				["TE"] = 1,
				["T1"] = {
				},
				["v"] = 1,
			},
		},
		["profileName"] = "Ohann",
		["questlog"] = {
		},
		["notes"] = {
		},
		["relation"] = {
			["0424120814axIg4"] = "BUSINESS",
		},
	},
}
TRP3_Characters = {
	["Awadwa-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Wadetosmun-ArgentDawn"] = {
		["profileID"] = "0301221101jbTao",
	},
	["Veirne-Quel'Thalas"] = {
		["profileID"] = "04172110102jBOC",
	},
	["Shirne-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Hbankeryucca-ArgentDawn"] = {
		["profileID"] = "0327213047JZwig",
	},
	["Yenuthie-ArgentDawn"] = {
		["profileID"] = "0429003812dNQzx",
		["chat_last_language_used"] = 1,
	},
	["Wfawfafw-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Awdfwa-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Yuccamailh-Quel'Thalas"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Tosmun-ArgentDawn"] = {
		["profileID"] = "0301221101jbTao",
	},
	["Liumea-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Grumgrobogr-ArgentDawn"] = {
		["profileID"] = "04172110102jBOC",
	},
	["Shidhewe-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Xioniu-ArgentDawn"] = {
		["profileID"] = "04172110102jBOC",
	},
	["Wadetos-ArgentDawn"] = {
		["profileID"] = "0301221101jbTao",
	},
	["Minsohu-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Sfagva-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Justformoun-ArgentDawn"] = {
		["profileID"] = "0405153352VjZNM",
	},
	["Dohoen-ArgentDawn"] = {
		["profileID"] = "0502195745HZ2rk",
	},
	["Dograem-ArgentDawn"] = {
		["profileID"] = "0409165547dmiRe",
	},
	["Gosheven-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Wadfwafwaf-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Tosmun-Drak'thul"] = {
		["profileID"] = "04172110102jBOC",
	},
	["Veirne-ArgentDawn"] = {
		["profileID"] = "04172110102jBOC",
	},
	["Yuccamaila-Quel'Thalas"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Yenuthile-ArgentDawn"] = {
		["chat_last_language_used"] = 1,
		["profileID"] = "0429003812dNQzx",
	},
	["Waafawg-ArgentDawn"] = {
		["chat_last_language_used"] = 7,
		["profileID"] = "04172110102jBOC",
	},
	["Joowei-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Abankeryucca-ArgentDawn"] = {
		["profileID"] = "0327213047JZwig",
	},
	["Gvaga-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Ohann-ArgentDawn"] = {
		["profileID"] = "0307210639PPtAO",
	},
	["Yenuthile-Drak'thul"] = {
		["profileID"] = "04172110102jBOC",
	},
	["Yuccabrankra-Drak'thul"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Kotexlevexmi-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
		["chat_last_language_used"] = 1,
	},
	["Swffwgwagw-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Granley-Quel'Thalas"] = {
		["profileID"] = "0405154200knylg",
	},
	["Rifeng-ArgentDawn"] = {
		["profileID"] = "0430190512nszsi",
	},
	["Tunea-ArgentDawn"] = {
		["profileID"] = "04172110102jBOC",
	},
	["Yeklie-ArgentDawn"] = {
		["profileID"] = "0429003812dNQzx",
	},
	["Bankeryuccaa-ArgentDawn"] = {
		["profileID"] = "0317204907TmkLj",
	},
	["Yuccabankerh-Drak'thul"] = {
		["profileID"] = "1016222047a3dXy",
	},
	["Wfawfafwa-ArgentDawn"] = {
		["profileID"] = "1016222047a3dXy",
	},
}
TRP3_Configuration = {
	["HIDE_MAP_BUTTON_IF_EMPTY"] = false,
	["toolbar_hide_title"] = false,
	["CONFIG_TARGET_POS_X"] = -93.81793212890625,
	["register_mature_filter"] = false,
	["CONFIG_GLANCE_PARENT"] = "TRP3_TargetFrame",
	["target_content_aa_player_b_music"] = true,
	["tooltip_char_combat"] = false,
	["default_profile_id"] = "1016222047a3dXy",
	["tooltip_char_target"] = true,
	["chat_ooc"] = true,
	["chat_show_ooc"] = true,
	["default_color_picker"] = true,
	["register_map_location_ooc"] = false,
	["chat_name"] = 3,
	["tooltip_prefere_ooc_icon"] = "TEXT",
	["target_icon_size"] = 30,
	["toolbar_show_on_login"] = true,
	["increase_color_contrast"] = true,
	["CONFIG_TARGET_POS_Y"] = -23.79153251647949,
	["minimap_show"] = true,
	["target_content_quest_action_LISTEN"] = true,
	["chat_use_CHAT_MSG_WHISPER"] = true,
	["tooltip_char_ooc"] = true,
	["tooltip_pets_owner"] = true,
	["tooltip_char_icons"] = true,
	["target_use"] = 1,
	["chat_yell_no_emote"] = false,
	["comm_broad_chan"] = "xtensionxtooltip2",
	["tooltip_char_pronouns"] = true,
	["tooltip_char_HideOriginal"] = true,
	["target_content_bb_companion_profile_mount"] = true,
	["comm_broad_use"] = true,
	["config_register_about_h2_size"] = 20,
	["remove_realm"] = true,
	["chat_ooc_pattern"] = "(%(.-%))",
	["tooltip_char_spacing"] = true,
	["chat_speech"] = true,
	["target_content_aa_player_w_mature_flag"] = true,
	["tooltip_pets_notif"] = true,
	["CONFIG_TOOLTIP_SIZE"] = 11,
	["chat_use_CHAT_MSG_YELL"] = true,
	["chat_insert_full_rp_name"] = true,
	["CONFIG_GLANCE_ANCHOR_X"] = 0,
	["extended_sounds_method"] = "p",
	["tooltip_char_terSize"] = 10,
	["chat_use_CHAT_MSG_OFFICER"] = true,
	["tooltip_char_color"] = true,
	["CONFIG_RIGHT_CLICK_OPEN_PROFILE"] = false,
	["register_auto_purge_mode"] = 864000,
	["CONFIG_RIGHT_CLICK_DISABLE_OOC"] = false,
	["chat_emote"] = true,
	["chat_use_CHAT_MSG_RAID"] = true,
	["tooltip_char_relation"] = true,
	["tooltip_char_mainSize"] = 16,
	["CONFIG_TARGET_POS_A"] = "TOP",
	["tooltip_char_current_lines"] = 4,
	["CONFIG_TOOLBAR_POS_A"] = "BOTTOMRIGHT",
	["toolbar_content_bb_extended_tools"] = true,
	["minimap_icon_position"] = {
		["minimapPos"] = 193.2552117452981,
		["hide"] = false,
	},
	["chat_use_CHAT_MSG_RAID_LEADER"] = true,
	["tooltip_no_fade_out"] = false,
	["tooltip_pets_info"] = true,
	["register_map_location_disable_war_mode"] = false,
	["CONFIG_GLANCE_TT_ANCHOR"] = "LEFT",
	["target_content_zzzzzzzzzz_player_report"] = true,
	["target_content_aa_player_e_inspect"] = true,
	["chat_emote_pattern"] = "(%*.-%*)",
	["chat_language_enabled_workaround_for_language_reset"] = true,
	["register_mature_filter_strength"] = 7,
	["chat_use_CHAT_MSG_PARTY"] = true,
	["extended_sounds_active"] = true,
	["tooltip_char_rc"] = true,
	["tooltip_char_guild"] = true,
	["tooltip_char_ft"] = true,
	["toolbar_content_hh_player_e_quest"] = true,
	["toolbar_content_aa_trp3_c"] = true,
	["toolbar_content_hh_player_d_inventory"] = true,
	["chat_ooc_color"] = "aa0015",
	["extended_sounds_maxrange"] = 100,
	["register_sanitization"] = true,
	["toolbar_content_aa_trp3_rpstatus"] = true,
	["target_content_aa_player_w_mature_white_list"] = true,
	["config_register_about_p_size"] = 12,
	["tooltip_char_Anchor"] = "ANCHOR_TOPRIGHT",
	["tooltip_in_character_only"] = false,
	["tooltip_profile_only"] = true,
	["tooltip_char_AnchoredFrame"] = "GameTooltip",
	["chat_color"] = true,
	["chat_use_CHAT_MSG_GUILD"] = true,
	["AddonLocale"] = "enUS",
	["tooltip_char_current_size"] = 140,
	["ui_animations"] = true,
	["MAKE_SURE_BROADCAST_CHANNEL_IS_LAST"] = true,
	["chat_npc_talk"] = true,
	["CONFIG_TOOLBAR_POS_Y"] = 40.62034225463867,
	["config_register_about_h3_size"] = 16,
	["tooltip_char_subSize"] = 12,
	["chat_use_CHAT_MSG_PARTY_LEADER"] = true,
	["extended_music_active"] = true,
	["tooltip_char_current"] = true,
	["target_content_aa_player_e_trade"] = true,
	["chat_use_CHAT_MSG_WHISPER_INFORM"] = true,
	["heavy_profile_alert"] = true,
	["new_version_alert"] = true,
	["register_map_location_show_war_modes"] = false,
	["target_content_bb_companion_profile"] = true,
	["ui_sounds"] = true,
	["chat_language_remember_last_used"] = true,
	["CONFIG_TOOLBAR_POS_X"] = -184.2783050537109,
	["AF_STUFF"] = false,
	["chat_show_icon"] = true,
	["toolbar_content_ww_trp3_languages"] = true,
	["chat_use_CHAT_MSG_EMOTE"] = true,
	["CONFIG_RIGHT_CLICK_OPEN_PROFILE_MODIFIER_KEY"] = 1,
	["chat_use_CHAT_MSG_SAY"] = true,
	["npc_talk_prefix"] = "|| ",
	["target_content_quest_action_LOOK"] = true,
	["toolbar_content_bb_extended_sounds"] = true,
	["CONFIG_GLANCE_ANCHOR_Y"] = -14,
	["target_content_aa_player_z_ignore"] = true,
	["tooltip_char_realm"] = true,
	["MAP_BUTTON_POSITION"] = "TOPLEFT",
	["target_content_quest_action_TALK"] = true,
	["config_register_about_h1_size"] = 25,
	["toolbar_content_bb_trp3_npctalk"] = true,
	["chat_disable_ooc"] = false,
	["chat_use_CHAT_MSG_TEXT_EMOTE"] = true,
	["MODULE_ACTIVATION"] = {
		["trp3_tinytooltip"] = true,
		["trp3_chatframes"] = true,
		["trp3_msp"] = true,
		["trp3_wim"] = true,
		["trp3_tooltips"] = true,
		["trp3_elvui_chat"] = true,
		["trp3_prat"] = true,
		["trp3_glance_bar"] = true,
		["trp3_tool_bar"] = true,
		["trp3_elvui"] = true,
		["trp3_target_bar"] = true,
		["trp3_extended"] = true,
		["trp3_mature_filter"] = true,
		["trp3_tiptac"] = true,
		["trp3_extended_tools"] = true,
	},
	["target_content_aa_player_d_relation"] = true,
	["toolbar_max_per_line"] = 7,
	["tooltip_crop_text"] = true,
	["tooltip_pets_icons"] = true,
	["tooltip_char_title"] = true,
	["toolbar_icon_size"] = 25,
	["CONFIG_GLANCE_LOCK"] = true,
	["register_map_location"] = true,
	["target_content_aa_player_w_mature_remove_white_list"] = true,
	["target_content_aa_player_a_page"] = true,
	["extended_weight_unit"] = "g",
	["extended_music_method"] = "a",
	["toolbar_content_bb_extended_drop"] = true,
	["target_content_za_notes"] = true,
	["tooltip_char_notif"] = true,
	["tooltip_pets_title"] = true,
	["target_content_quest_action_ACTION"] = true,
	["chat_npcspeech_replacement"] = true,
}
TRP3_Flyway = {
	["currentBuild"] = 12,
	["log"] = "Patch applied from 12 to 12 on 04/07/20 23:18:37",
}
TRP3_Presets = {
	["peek"] = {
	},
	["peekCategory"] = {
	},
}
TRP3_Companions = {
	["player"] = {
		["0324225041yVGS2"] = {
			["profileName"] = "Hermina",
			["PE"] = {
				["1"] = {
					["AC"] = true,
					["TI"] = "Chestnut",
					["TX"] = "-Hermina has chestnut color with white nose.",
					["IC"] = "inv_horse3_chestnut",
				},
				["2"] = {
					["AC"] = true,
					["TI"] = "Scars on left side",
					["TX"] = "-Hermina has scars on her left side of her face.\n-Part of left ear is missing.",
					["IC"] = "spell_druid_bloodythrash",
				},
				["v"] = 10,
			},
			["data"] = {
				["IC"] = "inv_horse3saddle001_chestnut",
				["BK"] = 1,
				["TI"] = "Horse",
				["NA"] = "Hermina",
				["v"] = 5,
			},
			["links"] = {
				["6648"] = "MOUNT",
			},
		},
	},
}
TRP3_MatureFilter = {
	["safeList"] = {
	},
	["dictionary"] = {
		["tongue in a"] = 1,
		["deep throat"] = 1,
		["darkie"] = 1,
		["boobs"] = 1,
		["twinkie"] = 1,
		["hentai"] = 1,
		["poopchute"] = 1,
		["bimbos"] = 1,
		["rape"] = 1,
		["double dong"] = 1,
		["bollocks"] = 1,
		["figging"] = 1,
		["sex"] = 1,
		["ball kicking"] = 1,
		["knobbing"] = 1,
		["doggie style"] = 1,
		["make me come"] = 1,
		["ball licking"] = 1,
		["arsehole"] = 1,
		["boner"] = 1,
		["orgy"] = 1,
		["carpet muncher"] = 1,
		["big breasts"] = 1,
		["male squirting"] = 1,
		["booty call"] = 1,
		["cornhole"] = 1,
		["bastinado"] = 1,
		["chocolate rosebuds"] = 1,
		["incest"] = 1,
		["menage a trois"] = 1,
		["ball sucking"] = 1,
		["beaner"] = 1,
		["footjob"] = 1,
		["butt"] = 1,
		["jack off"] = 1,
		["clitoris"] = 1,
		["bestiality"] = 1,
		["cunnilingus"] = 1,
		["clit"] = 1,
		["pedobear"] = 1,
		["beaver cleaver"] = 1,
		["scissoring"] = 1,
		["leather restraint"] = 1,
		["bitches"] = 1,
		["paedophile"] = 1,
		["black cock"] = 1,
		["camgirl"] = 1,
		["big knockers"] = 1,
		["vagina"] = 1,
		["undressing"] = 1,
		["bbw"] = 1,
		["milf"] = 1,
		["alabama hot pocket"] = 1,
		["doggystyle"] = 1,
		["nipples"] = 1,
		["pornography"] = 1,
		["tied up"] = 1,
		["acrotomophilia"] = 1,
		["hard core"] = 1,
		["jiggerboo"] = 1,
		["fecal"] = 1,
		["sadism"] = 1,
		["birdlock"] = 1,
		["camwhore"] = 1,
		["snowballing"] = 1,
		["how to kill"] = 1,
		["poontang"] = 1,
		["prince albert piercing"] = 1,
		["female squirting"] = 1,
		["strap on"] = 1,
		["goo girl"] = 1,
		["fuck buttons"] = 1,
		["fisting"] = 1,
		["sodomize"] = 1,
		["big black"] = 1,
		["reverse cowgirl"] = 1,
		["tushy"] = 1,
		["felch"] = 1,
		["bukkake"] = 1,
		["nawashi"] = 1,
		["porn"] = 1,
		["group sex"] = 1,
		["vulva"] = 1,
		["giant cock"] = 1,
		["venus mound"] = 1,
		["nymphomania"] = 1,
		["queaf"] = 1,
		["ball gag"] = 1,
		["throating"] = 1,
		["shaved pussy"] = 1,
		["butthole"] = 1,
		["nimphomania"] = 1,
		["nudity"] = 1,
		["yaoi"] = 1,
		["erotism"] = 1,
		["coprophilia"] = 1,
		["girl on top"] = 1,
		["shaved beaver"] = 1,
		["hand job"] = 1,
		["dirty sanchez"] = 1,
		["eunuch"] = 1,
		["date rape"] = 1,
		["apeshit"] = 1,
		["santorum"] = 1,
		["dommes"] = 1,
		["camslut"] = 1,
		["kinbaku"] = 1,
		["porno"] = 1,
		["god damn"] = 1,
		["titties"] = 1,
		["bastard"] = 1,
		["dingleberries"] = 1,
		["s&m"] = 1,
		["fudge packer"] = 1,
		["cunt"] = 1,
		["shit"] = 1,
		["twat"] = 1,
		["hooker"] = 1,
		["ejaculation"] = 1,
		["bunghole"] = 1,
		["violet wand"] = 1,
		["jerk off"] = 1,
		["tub girl"] = 1,
		["2 girls 1 cup"] = 1,
		["barenaked"] = 1,
		["assmunch"] = 1,
		["grope"] = 1,
		["lovemaking"] = 1,
		["skeet"] = 1,
		["fuck"] = 1,
		["honkey"] = 1,
		["jelly donut"] = 1,
		["frotting"] = 1,
		["fingering"] = 1,
		["fudgepacker"] = 1,
		["jailbait"] = 1,
		["daterape"] = 1,
		["bangbros"] = 1,
		["xxx"] = 1,
		["suck"] = 1,
		["wrinkled starfish"] = 1,
		["handjob"] = 1,
		["bitch"] = 1,
		["jizz"] = 1,
		["urophilia"] = 1,
		["urethra play"] = 1,
		["2g1c"] = 1,
		["bastardo"] = 1,
		["gang bang"] = 1,
		["muff diver"] = 1,
		["bullshit"] = 1,
		["homoerotic"] = 1,
		["penis"] = 1,
		["buttcheeks"] = 1,
		["femdom"] = 1,
		["faggot"] = 1,
		["pole smoker"] = 1,
		["hot carl"] = 1,
		["dick"] = 1,
		["ponyplay"] = 1,
		["doggiestyle"] = 1,
		["jail bait"] = 1,
		["spunk"] = 1,
		["boob"] = 1,
		["blonde on blonde action"] = 1,
		["g-spot"] = 1,
		["raping"] = 1,
		["humping"] = 1,
		["titty"] = 1,
		["how to murder"] = 1,
		["baby batter"] = 1,
		["blowjob"] = 1,
		["one cup two girls"] = 1,
		["neonazi"] = 1,
		["genitals"] = 1,
		["beaners"] = 1,
		["girls gone wild"] = 1,
		["yiffy"] = 1,
		["tea bagging"] = 1,
		["swinger"] = 1,
		["coprolagnia"] = 1,
		["blow job"] = 1,
		["nambla"] = 1,
		["style doggy"] = 1,
		["pisspig"] = 1,
		["splooge moose"] = 1,
		["ecchi"] = 1,
		["golden shower"] = 1,
		["blumpkin"] = 1,
		["brunette action"] = 1,
		["clover clamps"] = 1,
		["strapon"] = 1,
		["lolita"] = 1,
		["busty"] = 1,
		["big tits"] = 1,
		["dolcett"] = 1,
		["jigaboo"] = 1,
		["blow your load"] = 1,
		["barely legal"] = 1,
		["goregasm"] = 1,
		["sexy"] = 1,
		["shrimping"] = 1,
		["shitty"] = 1,
		["omorashi"] = 1,
		["sexo"] = 1,
		["alaskan pipeline"] = 1,
		["nsfw images"] = 1,
		["hot chick"] = 1,
		["fucktards"] = 1,
		["vorarephilia"] = 1,
		["smut"] = 1,
		["fucking"] = 1,
		["xx"] = 1,
		["tight white"] = 1,
		["baby juice"] = 1,
		["spooge"] = 1,
		["wetback"] = 1,
		["carpetmuncher"] = 1,
		["doggy style"] = 1,
		["zoophilia"] = 1,
		["anal"] = 1,
		["tranny"] = 1,
		["spread legs"] = 1,
		["swastika"] = 1,
		["rusty trombone"] = 1,
		["nipple"] = 1,
		["cum"] = 1,
		["scat"] = 1,
		["deepthroat"] = 1,
		["domination"] = 1,
		["nude"] = 1,
		["rimming"] = 1,
		["tribadism"] = 1,
		["foot fetish"] = 1,
		["motherfucker"] = 1,
		["upskirt"] = 1,
		["pthc"] = 1,
		["schlong"] = 1,
		["dendrophilia"] = 1,
		["queef"] = 1,
		["orgasm"] = 1,
		["rosy palm"] = 1,
		["escort"] = 1,
		["rectum"] = 1,
		["goatse"] = 1,
		["blonde action"] = 1,
		["missionary position"] = 1,
		["dry hump"] = 1,
		["bdsm"] = 1,
		["girl on"] = 1,
		["octopussy"] = 1,
		["ball sack"] = 1,
		["anus"] = 1,
		["circlejerk"] = 1,
		["babeland"] = 1,
		["futanari"] = 1,
		["rimjob"] = 1,
		["kike"] = 1,
		["voyeur"] = 1,
		["mound of venus"] = 1,
		["autoerotic"] = 1,
		["kinkster"] = 1,
		["masturbate"] = 1,
		["wet dream"] = 1,
		["bung hole"] = 1,
		["yellow showers"] = 1,
		["snatch"] = 1,
		["huge fat"] = 1,
		["clusterfuck"] = 1,
		["pegging"] = 1,
		["poon"] = 1,
		["anilingus"] = 1,
		["cocks"] = 1,
		["sodomy"] = 1,
		["gay sex"] = 1,
		["blue waffle"] = 1,
		["jiggaboo"] = 1,
		["dog style"] = 1,
		["panties"] = 1,
		["shemale"] = 1,
		["nig nog"] = 1,
		["double penetration"] = 1,
		["wank"] = 1,
		["shibari"] = 1,
		["dildo"] = 1,
		["panty"] = 1,
		["nigga"] = 1,
		["camel toe"] = 1,
		["taste my"] = 1,
		["sucks"] = 1,
		["slanteye"] = 1,
		["fingerbang"] = 1,
		["feltch"] = 1,
		["coons"] = 1,
		["pedophile"] = 1,
		["piece of shit"] = 1,
		["shota"] = 1,
		["cleveland steamer"] = 1,
		["brown showers"] = 1,
		["phone sex"] = 1,
		["beaver lips"] = 1,
		["pissing"] = 1,
		["ass"] = 1,
		["pussy"] = 1,
		["suicide girls"] = 1,
		["pleasure chest"] = 1,
		["bareback"] = 1,
		["tits"] = 1,
		["slut"] = 1,
		["dominatrix"] = 1,
		["goatcx"] = 1,
		["paki"] = 1,
		["tosser"] = 1,
		["coon"] = 1,
		["wrapping men"] = 1,
		["juggs"] = 1,
		["bulldyke"] = 1,
		["bullet vibe"] = 1,
		["goodpoop"] = 1,
		["two girls one cup"] = 1,
		["one guy one jar"] = 1,
		["punany"] = 1,
		["sultry women"] = 1,
		["raging boner"] = 1,
		["bondage"] = 1,
		["rosy palm and her 5 sisters"] = 1,
		["guro"] = 1,
		["dp action"] = 1,
		["tainted love"] = 1,
		["pubes"] = 1,
		["intercourse"] = 1,
		["quim"] = 1,
		["fellatio"] = 1,
		["raghead"] = 1,
		["piss pig"] = 1,
		["tit"] = 1,
		["asshole"] = 1,
		["dingleberry"] = 1,
		["vibrator"] = 1,
		["shitblimp"] = 1,
		["gokkun"] = 1,
		["hardcore"] = 1,
		["semen"] = 1,
		["poof"] = 1,
		["mr hands"] = 1,
		["spic"] = 1,
		["erotic"] = 1,
		["cock"] = 1,
		["negro"] = 1,
		["kinky"] = 1,
		["dirty pillows"] = 1,
		["twink"] = 1,
		["lemon party"] = 1,
		["poop chute"] = 1,
		["splooge"] = 1,
		["fuckin"] = 1,
		["white power"] = 1,
		["strappado"] = 1,
		["threesome"] = 1,
		["muffdiving"] = 1,
		["cumming"] = 1,
		["rapist"] = 1,
		["leather straight jacket"] = 1,
		["nigger"] = 1,
		["eat my ass"] = 1,
		["playboy"] = 1,
		["creampie"] = 1,
		["strip club"] = 1,
		["topless"] = 1,
		["tubgirl"] = 1,
		["towelhead"] = 1,
		["auto erotic"] = 1,
		["dvda"] = 1,
		["ball gravy"] = 1,
		["nympho"] = 1,
		["donkey punch"] = 1,
	},
}
TRP3_Colors = {
}
TRP3_Notes = {
}
